version: "3"
services:
  worker:
    build:
        context: .
    command: /bin/bash -c "php artisan schedule:work"
      
    environment:
      APP_NAME: Dental
      APP_ENV: local
      APP_KEY: base64:3rnog3KKdUAmh+IbdOIqFFhtECAqaurl/pEg9qY3inc=
      APP_DEBUG: 1
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: data
      DB_USERNAME: root
      DB_PASSWORD: tiger
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      REDIS_HOST: redis
      REDIS_PASSWORD: 1234
      REDIS_PORT: 6379
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: mdumont567@gmail.com
      MAIL_PASSWORD: xyeyuhwdpskvrkwe
      MAIL_ENCRYPTION: tls
      PUSHER_APP_ID:
      PUSHER_APP_KEY:
      PUSHER_APP_SECRET:
      PUSHER_APP_CLUSTER: mt1
      MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
      MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
      AWS_ACCESS_KEY_ID: AKIAYKLJBI5DGKNIL7MU
      AWS_BUCKET: populando
      AWS_DEFAULT_REGION: us-west-1
      AWS_SECRET_ACCESS_KEY: FdIptx+VeQkWY84hVK37E+L0bYOe5Ramfc3muvd8
      AWS_URL: https://populando.s3-us-west-1.amazonaws.com
      URL_LOGO: ""
      JUND_HOST: http://melc-moto.ddns.net:6080/wsJUNDSOFT_FULL_V1.asmx
      JUND_CNPJ: 50770031
      JUND_USER: wms
      JUND_PASSWORD: 1234
      INSPECTOR_INGESTION_KEY: 4b3709324f2c8eb2196e59241305055e6ac75aae


    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./default.conf:/etc/apache2/sites-enabled/default.conf
    networks:
      - default

  webserver:
    build:
        context: .
    command: /bin/bash -c "composer install && npm install && php artisan migrate && chmod 777 -R ./storage && npm install && php artisan octane:start --watch --server=swoole --host=0.0.0.0 --port=8000"
    ports:
       - "89:8000"
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:3rnog3KKdUAmh+IbdOIqFFhtECAqaurl/pEg9qY3inc=
      APP_DEBUG: 1
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: data
      DB_USERNAME: root
      DB_PASSWORD: tiger
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      REDIS_HOST: redis
      REDIS_PASSWORD: 1234
      REDIS_PORT: 6379
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: mdumont567@gmail.com
      MAIL_PASSWORD: xyeyuhwdpskvrkwe
      MAIL_ENCRYPTION: tls
      PUSHER_APP_ID:
      PUSHER_APP_KEY:
      PUSHER_APP_SECRET:
      PUSHER_APP_CLUSTER: mt1
      MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
      MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
      AWS_ACCESS_KEY_ID: AKIAYKLJBI5DGKNIL7MU
      AWS_BUCKET: populando
      AWS_DEFAULT_REGION: us-west-1
      AWS_SECRET_ACCESS_KEY: FdIptx+VeQkWY84hVK37E+L0bYOe5Ramfc3muvd8
      AWS_URL: https://populando.s3-us-west-1.amazonaws.com
      URL_LOGO: ""
      JUND_HOST: http://melc-moto.ddns.net:6080/wsJUNDSOFT_FULL_V1.asmx
      JUND_CNPJ: 50770031
      JUND_USER: wms
      JUND_PASSWORD: 1234
      INSPECTOR_INGESTION_KEY: 4b3709324f2c8eb2196e59241305055e6ac75aae


    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./default.conf:/etc/apache2/sites-enabled/default.conf
    networks:
      - default

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: data
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - redis
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8086:80'
    volumes:
      - /sessions
    networks:
      - default
  redis:
    image: redis
    command: redis-server --requirepass 1234
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_PASSWORD=1234
    networks:
      - default

networks:
  default:

